#!/bin/bash

# --- CONFIGURATION START ---
AUTO_CLEAN=false
AUTO_AUTOREMOVE=false
# --- CONFIGURATION END ---

#change config
#sudo sed -i "s/^AUTO_CLEAN=.*/AUTO_CLEAN=true/" "$0"

help() {
  echo "version 1.1.3"
  echo "Usage: fastapt <commande> [options]"
  echo "Commandes disponibles :"
  echo "  u | update              - Met à jour les paquets et propose une mise à niveau"
  echo "  s | search <mot-clé>    - Recherche dans les paquets installés"
  echo "  r | remove <pkg>        - Supprime un paquet, option purge proposée"
  echo "  e | edit                - Édite les sources APT"
  echo "  h | help                - Affiche cette aide"
  echo " su | self-update         - Met à jour ce script"
}

edition_de_source() {
    local supprimer="$1"

    if [ "$supprimer" ==  "-r" ]; then
      fichier=$(ls /etc/apt/sources.list.d/ | fzf --prompt="Choisis un fichier à supprimer: ")
      if [ -n "$fichier" ]; then
        sudo rm /etc/apt/sources.list.d/$fichier
      else
        echo "Aucun fichier sélectionné"
      fi
    else
      fichier=$(ls /etc/apt/sources.list.d/ | fzf --prompt="Choisis un fichier à éditer: ")
      if [ -n "$fichier" ]; then
        sudo nano /etc/apt/sources.list.d/$fichier
      else
        echo "Aucun fichier sélectionné"
      fi
    fi
}

case "$1" in
  update|u)
    echo "[+] Mise à jour des paquets..."
    sudo apt update
    upgradable=$(apt list --upgradable 2>/dev/null | grep -c "/")

    if [ "$upgradable" -eq 0 ]; then
      echo "[-] Tous les paquets sont à jour."
    else
      echo "appuyer sur q pour quitter la liste des paquets"
      echo
      apt list --upgradable
      echo
      echo "[?] Voulez-vous mettre à niveau les paquets disponibles ? (y/n)"
      read -r upgrade_confirm
      if [[ "$upgrade_confirm" == "y" || "$upgrade_confirm" == "Y" ]]; then
        echo "[+] Mise à niveau des paquets..."
        if [ "$2" ==  "-y" ]; then
          sudo apt upgrade -y
        else
          sudo apt upgrade
        fi
        if [ "$AUTO_CLEAN" = true ]; then
          sudo apt-get clean
          echo "[+] apt-get clean"
        fi
        if [ "$AUTO_AUTOREMOVE" = true ]; then
          sudo apt autoremove
          echo "[+] apt autoremove"
        fi
      else
        echo "[-] Mise à niveau annulée."
      fi
    fi
    ;;

  search|s)
    if [ -z "$2" ]; then
      if command -v fzf >/dev/null 2>&1; then
        apt list | fzf
      else
        echo "fzf n'est pas installé ❌"
        echo
        echo "[?] Voulez-vous installé fzf ? (y/n)"
        read -r install_fzf_confirm
        if [[ "$install_fzf_confirm" == "y" || "$install_fzf_confirm" == "Y" ]]; then
            sudo apt install fzf
            apt list | fzf
        else
            echo "[-] Installation de fzf annulée."
        fi
      fi
    else
      echo "[+] Recherche de paquets contenant '$2'..."
      sudo apt list --installed | grep "$2"
    fi
    ;;

  remove|r)
    if [ -z "$2" ]; then
      echo "Usage: fastapt remove <nom-paquet>"
    else
      echo "[?] Voulez-vous aussi supprimer les fichiers de configuration ? (purge) (y/n)"
      read -r purge_confirm
      if [[ "$purge_confirm" == "y" || "$purge_confirm" == "Y" ]]; then
        echo "[+] Suppression complète de '$2' avec purge..."
        if [ "$3" ==  "-y" ]; then
          sudo apt purge "$2" -y
        else
          sudo apt purge "$2"
        fi
      else
        echo "[+] Suppression de '$2'..."
        if [ "$3" ==  "-y" ]; then
          sudo apt remove "$2" -y
        else
          sudo apt remove "$2"
        fi
      fi
    fi
    ;;

  edit|e)

    if command -v fzf >/dev/null 2>&1; then
        edition_de_source "$2"
    else
        echo "fzf n'est pas installé ❌"
        echo
        echo "[?] Voulez-vous installé fzf ? (y/n)"
        read -r install_fzf_confirm
        if [[ "$install_fzf_confirm" == "y" || "$install_fzf_confirm" == "Y" ]]; then
            sudo apt install fzf
            edition_de_source "$2"
        else
            echo "[-] Installation de fzf annulée."
        fi
    fi
    ;;

  self-update|su)
    sudo curl -L "https://raw.githubusercontent.com/aqua47/Fastapt/refs/heads/main/fastapt" -o /usr/local/bin/fastapt && sudo chmod +x /usr/local/bin/fastapt
    ;;

  help|h)
    help
    ;;

  *)
    echo "Commande inconnue: '$1'"
    help
    ;;
esac
